#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1601037053                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : au                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/apex-appointments-extended/id1601037053  # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/180.png                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Apex                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Appointments Extended                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Transform your calendar into a communication tool with Apex. This intuitive, week-based calendar app effortlessly keeps you in touch with everyone in your appointments.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                                 
your_link                                 :                      
your_city                                 :                              
email_address                             : apexappointmentsextended@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Smart appointments
    description                           : Apex detects Contacts, phone numbers and email addresses in iOS calendar appointments then provides quick communication options
    fontawesome_icon_name                 : mobile
    
  - title                                 : Quickly send text & emails from prebuilt templates
    description                           : Send appointment reminders to a client, ask for a review or confirm the next booking without entering any text. Set up your template once and Apex will pull the data from your appointment, Contact or custom data tags
    fontawesome_icon_name                 : mobile

  - title                                 : Build templates easily
    description                           : Drag and Drop Contact, calendar or even custom data tags into text and email templates
    fontawesome_icon_name                 : mobile

  - title                                 : Maps
    description                           : Choose Apple or Google Maps to find an appointment's location or get directions from a button tap
    fontawesome_icon_name                 : mobile

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 1.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#00BBFF"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#00BBFF"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
